### ISSUE TITLE
test with incorrect time Strings

### ISSUE THREAD

**Issue by ArthurPaivaT** [SkyTradeLinks/solana-rental#32]
```[tasklist]
### Tasks
- [x] 3 months in the future dateTime should fail
- [x] invalid iso string should fail
- [x] times that are not round of 30 minutes should fail
```
